// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "L1X",
    "description": "L1X Creative Agency"
  },

  "ChangeLang": { "label": "Change Language" },

  "Hero": { "title": "CREATIVE AGENCY", "button": "Our Services" },

  "Services": {
    "title": "Our Services",
    "cards": {
      "card_1": { "title": "Service 1", "description": "Service" },
      "card_2": { "title": "Service 2", "description": "Service" },
      "card_3": { "title": "Service 3", "description": "Service" }
    }
  },

  "Portfolio": {
    "title": "Portfolio"
  },

  "Contact": {
    "highlight": "Start your journey",
    "title": "Your story starts here",
    "description": "Whether you're ready to start or just exploring options, our team is here to help guide your creative journey.",
    "quote": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",

    "user": {
      "name": "Lorem ipsum",
      "role": "Lorem ipsum dolor sit"
    },

    "clients": {
      "number": "123,000",
      "title": "our clients"
    },

    "form": {
      "title": "Contact Us",
      "firstname": "First name",
      "lastname": "Last name",
      "email": "Email",
      "company": "Company name",
      "message": "Message",
      "confirm": "Confirm"
    }
  },

  "Footer": {
    "services": "Services",
    "portfolio": "Portfolio",
    "contact": "Contact Us"
  }
};
export default messages;