// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "L1X",
    "description": "L1X Creative Agency"
  },

  "ChangeLang": { "label": "Change Language" },

  "Hero": { "title": "CREATIVE AGENCY", "button": "Our Services" },

  "Services": {
    "title": "Our Services",
    "cards": {
      "card_1": { "title": "Service 1", "description": "Service" },
      "card_2": { "title": "Service 2", "description": "Service" },
      "card_3": { "title": "Service 3", "description": "Service" }
    }
  },

  "Portfolio": {
    "title": "Portfolio"
  },

  "Contact": {
    "highlight": "Lorem ipsum dolor sit",
    "title": "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis sapiente distinctio aliquam eaque quia sed facilis ratione ipsum mollitia, fugit nam voluptatum suscipit porro dolore animi eius perferendis est. Odio",
    "quote": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",

    "user": {
      "name": "Lorem ipsum",
      "role": "Lorem ipsum dolor sit"
    },

    "clients": {
      "number": "123,000",
      "title": "Lorem ipsum dolor sit"
    },

    "form": {
      "title": "Contact Us",
      "firstname": "First name",
      "lastname": "Last name",
      "email": "Email",
      "company": "Company name",
      "message": "Message",
      "confirm": "Confirm"
    }
  },

  "Footer": {
    "services": "Services",
    "portfolio": "Portfolio",
    "contact": "Contact Us"
  }
};
export default messages;